import fs from 'node:fs';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
const h = JSON.parse(fs.readFileSync(process.argv[2] || new URL('../../tickets.interpark.com_new.har', import.meta.url)));
const entries = h.log.entries;
const index = key => entries.findIndex(e => e.request.url.includes(key));
const pre = entries.findIndex(e => e.request.postData?.text?.includes('mutation PreselectSeat('));
const lock = index('/seats/select');
assert.ok(pre >= 0 && lock > pre);
const preBody = JSON.parse(entries[pre].request.postData.text);
const lockBody = JSON.parse(entries[lock].request.postData.text);
assert.equal(preBody.variables.command.seatInfoId, lockBody.seats[0].seatInfoId);
assert.equal(preBody.variables.command.playSeq, lockBody.playSeq);
const code = entries.filter(e => e.response.content.mimeType?.includes('javascript')).map(e => e.response.content.text || '').join('\n');
assert.ok(code.includes('onChange:v,onKeyUp:g'));
assert.ok(code.includes('6===s.length'));
assert.ok(code.includes('seatSelected:t'));
assert.ok(code.includes('seatSelectHandler:r'));
assert.ok(code.includes('onComplete:l'));
assert.ok(code.includes('interpark/captchaVerify'));
assert.ok(code.includes('r.push("/seat?step=price")'));
const init = entries.find(e => e.request.url.endsWith('/onestop/gql') && e.response.content.text?.includes('"initSeat"')); 
assert.ok(JSON.parse(init.response.content.text).data.initSeat.ticketMaxCount > 0);
console.log('新 HAR 契约通过：六位字母验证码、DOM/React 属性、预选→锁票顺序、座位场次一致、票数限制与 price 跳转');
